// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Attio.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Attio.OpenApiClient.V2.Emails
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\emails
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EmailsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.V2.Emails.EmailsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmailsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/emails{?cursor*,domain*,limit*,linked_object*,linked_record_ids*,participants*,sent_after*,sent_before*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.V2.Emails.EmailsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmailsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/emails{?cursor*,domain*,limit*,linked_object*,linked_record_ids*,participants*,sent_after*,sent_before*}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;Lists email metadata from your workspace&apos;s connected mailboxes. Email content is never returned.At least one of `linked_object` with `linked_record_ids`, `participants`, or `domain` must be supplied; there is no way to list every email. When several are supplied they are combined with OR: emails matching any of the filters are returned.&gt; **Requesting access:** this endpoint is enabled per workspace and per app while it is in alpha. Contact [support@attio.com](mailto:support@attio.com) to request access.**Things to know**- Filters that identify your own workspace are ignored. This covers a member&apos;s or invited member&apos;s address, one of your mailboxes, and any of their domains. If every filter you supply is ignored, an empty page is returned.- A filter that names a protected recipient in your workspace is rejected rather than ignored. This covers an address, a domain, and a record that resolves to either.- Emails from a mailbox shared with your workspace as metadata only are returned without a subject line. An email is left out entirely when it has no participant you may see — that is, when every participant outside your workspace is a protected recipient.- An email that reached more than one of your mailboxes is returned once, and `id.mailbox_id` identifies whichever copy was readable.- `linked_records` is derived when you make the request rather than stored, so it reflects your records as they are now.- Emails are returned newest first, ordered by when they were sent. Each request scans a bounded number of emails, so a page can hold fewer emails than `limit`, or none at all, while more are still available. Keep paginating for as long as a `next_cursor` is returned, rather than stopping on a short page.This endpoint is in alpha and may be subject to breaking changes as we gather feedback.Required scopes: `email:read`, `record_permission:read`, `object_configuration:read`.&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2Emails200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Attio.OpenApiClient.Models.GetV2Emails200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Attio.OpenApiClient.V2.Emails.EmailsRequestBuilder.EmailsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Attio.OpenApiClient.Models.GetV2Emails200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Attio.OpenApiClient.V2.Emails.EmailsRequestBuilder.EmailsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Attio.OpenApiClient.Models.GetV2Emails200Response>(requestInfo, global::Soenneker.Attio.OpenApiClient.Models.GetV2Emails200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Lists email metadata from your workspace&apos;s connected mailboxes. Email content is never returned.At least one of `linked_object` with `linked_record_ids`, `participants`, or `domain` must be supplied; there is no way to list every email. When several are supplied they are combined with OR: emails matching any of the filters are returned.&gt; **Requesting access:** this endpoint is enabled per workspace and per app while it is in alpha. Contact [support@attio.com](mailto:support@attio.com) to request access.**Things to know**- Filters that identify your own workspace are ignored. This covers a member&apos;s or invited member&apos;s address, one of your mailboxes, and any of their domains. If every filter you supply is ignored, an empty page is returned.- A filter that names a protected recipient in your workspace is rejected rather than ignored. This covers an address, a domain, and a record that resolves to either.- Emails from a mailbox shared with your workspace as metadata only are returned without a subject line. An email is left out entirely when it has no participant you may see — that is, when every participant outside your workspace is a protected recipient.- An email that reached more than one of your mailboxes is returned once, and `id.mailbox_id` identifies whichever copy was readable.- `linked_records` is derived when you make the request rather than stored, so it reflects your records as they are now.- Emails are returned newest first, ordered by when they were sent. Each request scans a bounded number of emails, so a page can hold fewer emails than `limit`, or none at all, while more are still available. Keep paginating for as long as a `next_cursor` is returned, rather than stopping on a short page.This endpoint is in alpha and may be subject to breaking changes as we gather feedback.Required scopes: `email:read`, `record_permission:read`, `object_configuration:read`.&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Attio.OpenApiClient.V2.Emails.EmailsRequestBuilder.EmailsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Attio.OpenApiClient.V2.Emails.EmailsRequestBuilder.EmailsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.V2.Emails.EmailsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Attio.OpenApiClient.V2.Emails.EmailsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Attio.OpenApiClient.V2.Emails.EmailsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;Lists email metadata from your workspace&apos;s connected mailboxes. Email content is never returned.At least one of `linked_object` with `linked_record_ids`, `participants`, or `domain` must be supplied; there is no way to list every email. When several are supplied they are combined with OR: emails matching any of the filters are returned.&gt; **Requesting access:** this endpoint is enabled per workspace and per app while it is in alpha. Contact [support@attio.com](mailto:support@attio.com) to request access.**Things to know**- Filters that identify your own workspace are ignored. This covers a member&apos;s or invited member&apos;s address, one of your mailboxes, and any of their domains. If every filter you supply is ignored, an empty page is returned.- A filter that names a protected recipient in your workspace is rejected rather than ignored. This covers an address, a domain, and a record that resolves to either.- Emails from a mailbox shared with your workspace as metadata only are returned without a subject line. An email is left out entirely when it has no participant you may see — that is, when every participant outside your workspace is a protected recipient.- An email that reached more than one of your mailboxes is returned once, and `id.mailbox_id` identifies whichever copy was readable.- `linked_records` is derived when you make the request rather than stored, so it reflects your records as they are now.- Emails are returned newest first, ordered by when they were sent. Each request scans a bounded number of emails, so a page can hold fewer emails than `limit`, or none at all, while more are still available. Keep paginating for as long as a `next_cursor` is returned, rather than stopping on a short page.This endpoint is in alpha and may be subject to breaking changes as we gather feedback.Required scopes: `email:read`, `record_permission:read`, `object_configuration:read`.&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EmailsRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("domain")]
            public string? Domain { get; set; }
#nullable restore
#else
            [QueryParameter("domain")]
            public string Domain { get; set; }
#endif
            [QueryParameter("limit")]
            public int? Limit { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("linked_object")]
            public string? LinkedObject { get; set; }
#nullable restore
#else
            [QueryParameter("linked_object")]
            public string LinkedObject { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("linked_record_ids")]
            public string? LinkedRecordIds { get; set; }
#nullable restore
#else
            [QueryParameter("linked_record_ids")]
            public string LinkedRecordIds { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("participants")]
            public string? Participants { get; set; }
#nullable restore
#else
            [QueryParameter("participants")]
            public string Participants { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sent_after")]
            public string? SentAfter { get; set; }
#nullable restore
#else
            [QueryParameter("sent_after")]
            public string SentAfter { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sent_before")]
            public string? SentBefore { get; set; }
#nullable restore
#else
            [QueryParameter("sent_before")]
            public string SentBefore { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
