// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Attio.OpenApiClient.V2.Sequences.Unsubscribed_emails;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Attio.OpenApiClient.V2.Sequences
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\sequences
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SequencesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The unsubscribed_emails property</summary>
        public global::Soenneker.Attio.OpenApiClient.V2.Sequences.Unsubscribed_emails.Unsubscribed_emailsRequestBuilder Unsubscribed_emails
        {
            get => new global::Soenneker.Attio.OpenApiClient.V2.Sequences.Unsubscribed_emails.Unsubscribed_emailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.V2.Sequences.SequencesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SequencesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/sequences", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.V2.Sequences.SequencesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SequencesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/sequences", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
