// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>The issuer of the token. Always attio.com</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AttioComIss
    {
        [EnumMember(Value = "attio.com")]
        #pragma warning disable CS1591
        AttioCom,
        #pragma warning restore CS1591
    }
}
