// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateBranch2"/>, <see cref="global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateBranch3"/>, <see cref="global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateWrapper"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AttributeDefaultValueAnyOf1Template : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateBranch2? AttributeDefaultValueAnyOf1TemplateBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateBranch2 AttributeDefaultValueAnyOf1TemplateBranch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateBranch3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateBranch3? AttributeDefaultValueAnyOf1TemplateBranch3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateBranch3 AttributeDefaultValueAnyOf1TemplateBranch3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateWrapper? AttributeDefaultValueAnyOf1TemplateWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateWrapper AttributeDefaultValueAnyOf1TemplateWrapper { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1Template"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1Template CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1Template();
            result.AttributeDefaultValueAnyOf1TemplateBranch2 = new global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateBranch2();
            result.AttributeDefaultValueAnyOf1TemplateBranch3 = new global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateBranch3();
            result.AttributeDefaultValueAnyOf1TemplateWrapper = new global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateWrapper();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AttributeDefaultValueAnyOf1TemplateBranch2 != null || AttributeDefaultValueAnyOf1TemplateBranch3 != null || AttributeDefaultValueAnyOf1TemplateWrapper != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AttributeDefaultValueAnyOf1TemplateBranch2, AttributeDefaultValueAnyOf1TemplateBranch3, AttributeDefaultValueAnyOf1TemplateWrapper);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.AttributeDefaultValueAnyOf1TemplateBranch2>(null, AttributeDefaultValueAnyOf1TemplateBranch2, AttributeDefaultValueAnyOf1TemplateBranch3, AttributeDefaultValueAnyOf1TemplateWrapper);
        }
    }
}
#pragma warning restore CS0618
