// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Comment : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Who wrote this comment. Note that the API provides the ability for API tokens to write comments on behalf of other actors.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.CommentAuthor? Author { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.CommentAuthor Author { get; set; }
#endif
        /// <summary>A plaintext representation of the content of the comment. References to workspace members are cast into email addresses, all other stylistic elements are removed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentPlaintext { get; set; }
#nullable restore
#else
        public string ContentPlaintext { get; set; }
#endif
        /// <summary>When the note was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The entry the comment belongs to, `null` for comments on records.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.CommentEntry? Entry { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.CommentEntry Entry { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.CommentId? Id { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.CommentId Id { get; set; }
#endif
        /// <summary>The record the comment belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.CommentRecord? Record { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.CommentRecord Record { get; set; }
#endif
        /// <summary>Whether the comment is resolved.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResolvedAt { get; set; }
#nullable restore
#else
        public string ResolvedAt { get; set; }
#endif
        /// <summary>The actor that resolved this comment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.CommentResolvedBy? ResolvedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.CommentResolvedBy ResolvedBy { get; set; }
#endif
        /// <summary>The ID of the thread the comment belongs to.</summary>
        public Guid? ThreadId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.Comment"/> and sets the default values.
        /// </summary>
        public Comment()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.Comment"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.Comment CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.Comment();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "author", n => { Author = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.CommentAuthor>(global::Soenneker.Attio.OpenApiClient.Models.CommentAuthor.CreateFromDiscriminatorValue); } },
                { "content_plaintext", n => { ContentPlaintext = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "entry", n => { Entry = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.CommentEntry>(global::Soenneker.Attio.OpenApiClient.Models.CommentEntry.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.CommentId>(global::Soenneker.Attio.OpenApiClient.Models.CommentId.CreateFromDiscriminatorValue); } },
                { "record", n => { Record = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.CommentRecord>(global::Soenneker.Attio.OpenApiClient.Models.CommentRecord.CreateFromDiscriminatorValue); } },
                { "resolved_at", n => { ResolvedAt = n.GetStringValue(); } },
                { "resolved_by", n => { ResolvedBy = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.CommentResolvedBy>(global::Soenneker.Attio.OpenApiClient.Models.CommentResolvedBy.CreateFromDiscriminatorValue); } },
                { "thread_id", n => { ThreadId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.CommentAuthor>("author", Author);
            writer.WriteStringValue("content_plaintext", ContentPlaintext);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.CommentEntry>("entry", Entry);
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.CommentId>("id", Id);
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.CommentRecord>("record", Record);
            writer.WriteStringValue("resolved_at", ResolvedAt);
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.CommentResolvedBy>("resolved_by", ResolvedBy);
            writer.WriteGuidValue("thread_id", ThreadId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
