// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConnectedFile : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Timestamp representing when the file entry was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The actor that created this file entry.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileCreatedByActor? CreatedByActor { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileCreatedByActor CreatedByActor { get; set; }
#endif
        /// <summary>The file ID in the external storage provider.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalProviderFileId { get; set; }
#nullable restore
#else
        public string ExternalProviderFileId { get; set; }
#endif
        /// <summary>The type of file entry.</summary>
        public global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileFileType? FileType { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileId? Id { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileId Id { get; set; }
#endif
        /// <summary>Microsoft drive ID. This field is only populated for `microsoft-onedrive` entries.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MicrosoftDriveId { get; set; }
#nullable restore
#else
        public string MicrosoftDriveId { get; set; }
#endif
        /// <summary>The ID of the object the record belongs to.</summary>
        public Guid? ObjectId { get; set; }
        /// <summary>The slug of the object the record belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectSlug { get; set; }
#nullable restore
#else
        public string ObjectSlug { get; set; }
#endif
        /// <summary>The ID of the record the file is linked to.</summary>
        public Guid? RecordId { get; set; }
        /// <summary>The storage provider for this file entry.</summary>
        public global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileStorageProvider? StorageProvider { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.ConnectedFile"/> and sets the default values.
        /// </summary>
        public ConnectedFile()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.ConnectedFile"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.ConnectedFile CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.ConnectedFile();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "created_by_actor", n => { CreatedByActor = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileCreatedByActor>(global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileCreatedByActor.CreateFromDiscriminatorValue); } },
                { "external_provider_file_id", n => { ExternalProviderFileId = n.GetStringValue(); } },
                { "file_type", n => { FileType = n.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileFileType>(); } },
                { "id", n => { Id = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileId>(global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileId.CreateFromDiscriminatorValue); } },
                { "microsoft_drive_id", n => { MicrosoftDriveId = n.GetStringValue(); } },
                { "object_id", n => { ObjectId = n.GetGuidValue(); } },
                { "object_slug", n => { ObjectSlug = n.GetStringValue(); } },
                { "record_id", n => { RecordId = n.GetGuidValue(); } },
                { "storage_provider", n => { StorageProvider = n.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileStorageProvider>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileCreatedByActor>("created_by_actor", CreatedByActor);
            writer.WriteStringValue("external_provider_file_id", ExternalProviderFileId);
            writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileFileType>("file_type", FileType);
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileId>("id", Id);
            writer.WriteStringValue("microsoft_drive_id", MicrosoftDriveId);
            writer.WriteGuidValue("object_id", ObjectId);
            writer.WriteStringValue("object_slug", ObjectSlug);
            writer.WriteGuidValue("record_id", RecordId);
            writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.ConnectedFileStorageProvider>("storage_provider", StorageProvider);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
