// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Email : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the email was sent from your workspace or received by it.</summary>
        public global::Soenneker.Attio.OpenApiClient.Models.EmailDirection? Direction { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.EmailId? Id { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.EmailId Id { get; set; }
#endif
        /// <summary>The person and company records whose email addresses or domains match this email&apos;s participants. Unlike meetings, this link is derived when you make the request rather than stored, so it reflects your records as they are now: creating a person record today will make older emails start reporting it.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.EmailLinkedRecordsItem>? LinkedRecords { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.EmailLinkedRecordsItem> LinkedRecords { get; set; }
#endif
        /// <summary>The participants on the email. Note that `bcc` participants are realistically only present on outbound email: inbound messages do not disclose the other recipients&apos; blind copies, so an absent `bcc` participant is not evidence that there was none.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.EmailParticipantsItem>? Participants { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.EmailParticipantsItem> Participants { get; set; }
#endif
        /// <summary>Timestamp representing when the email was sent, taken from the email&apos;s own headers rather than from when Attio imported it.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SentAt { get; set; }
#nullable restore
#else
        public string SentAt { get; set; }
#endif
        /// <summary>The subject line of the email. This is `null` when the email has no subject or is from a mailbox shared as metadata only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubjectLine { get; set; }
#nullable restore
#else
        public string SubjectLine { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.Email"/> and sets the default values.
        /// </summary>
        public Email()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.Email"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.Email CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.Email();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "direction", n => { Direction = n.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.EmailDirection>(); } },
                { "id", n => { Id = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.EmailId>(global::Soenneker.Attio.OpenApiClient.Models.EmailId.CreateFromDiscriminatorValue); } },
                { "linked_records", n => { LinkedRecords = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.EmailLinkedRecordsItem>(global::Soenneker.Attio.OpenApiClient.Models.EmailLinkedRecordsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "participants", n => { Participants = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.EmailParticipantsItem>(global::Soenneker.Attio.OpenApiClient.Models.EmailParticipantsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sent_at", n => { SentAt = n.GetStringValue(); } },
                { "subject_line", n => { SubjectLine = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.EmailDirection>("direction", Direction);
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.EmailId>("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.EmailLinkedRecordsItem>("linked_records", LinkedRecords);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.EmailParticipantsItem>("participants", Participants);
            writer.WriteStringValue("sent_at", SentAt);
            writer.WriteStringValue("subject_line", SubjectLine);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
