// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>Whether the email was sent from your workspace or received by it.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EmailDirection
    {
        [EnumMember(Value = "inbound")]
        #pragma warning disable CS1591
        Inbound,
        #pragma warning restore CS1591
        [EnumMember(Value = "outbound")]
        #pragma warning disable CS1591
        Outbound,
        #pragma warning restore CS1591
    }
}
