// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200ResponseAnyOf1"/>, <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200ResponseAnyOf2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetV2Self200Response : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200ResponseAnyOf1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200ResponseAnyOf1? GetV2Self200ResponseAnyOf1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200ResponseAnyOf1 GetV2Self200ResponseAnyOf1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200ResponseAnyOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200ResponseAnyOf2? GetV2Self200ResponseAnyOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200ResponseAnyOf2 GetV2Self200ResponseAnyOf2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200Response();
            result.GetV2Self200ResponseAnyOf1 = new global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200ResponseAnyOf1();
            result.GetV2Self200ResponseAnyOf2 = new global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200ResponseAnyOf2();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(GetV2Self200ResponseAnyOf1 != null || GetV2Self200ResponseAnyOf2 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GetV2Self200ResponseAnyOf1, GetV2Self200ResponseAnyOf2);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200ResponseAnyOf1>(null, GetV2Self200ResponseAnyOf1, GetV2Self200ResponseAnyOf2);
        }
    }
}
#pragma warning restore CS0618
