// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetV2ListsByListEntriesByEntryId200ResponseDataId : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A UUID identifying this entry.</summary>
        public Guid? EntryId { get; set; }
        /// <summary>A UUID identifying the list this entry is in.</summary>
        public Guid? ListId { get; set; }
        /// <summary>A UUID identifying the workspace this entry belongs to.</summary>
        public Guid? WorkspaceId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2ListsByListEntriesByEntryId200ResponseDataId"/> and sets the default values.
        /// </summary>
        public GetV2ListsByListEntriesByEntryId200ResponseDataId()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2ListsByListEntriesByEntryId200ResponseDataId"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.GetV2ListsByListEntriesByEntryId200ResponseDataId CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.GetV2ListsByListEntriesByEntryId200ResponseDataId();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "entry_id", n => { EntryId = n.GetGuidValue(); } },
                { "list_id", n => { ListId = n.GetGuidValue(); } },
                { "workspace_id", n => { WorkspaceId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("entry_id", EntryId);
            writer.WriteGuidValue("list_id", ListId);
            writer.WriteGuidValue("workspace_id", WorkspaceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
