// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>
    /// An object with `attribute_slug` keys, and an array of value objects as the values. Attributes slugs (for example `domains` or `name`) can be used, including custom attribute slugs.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValues : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The angellist property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesAngellistItem>? Angellist { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesAngellistItem> Angellist { get; set; }
#endif
        /// <summary>The categories property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesCategoriesItem>? Categories { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesCategoriesItem> Categories { get; set; }
#endif
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesCreatedAtItem>? CreatedAt { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesCreatedAtItem> CreatedAt { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesDescriptionItem>? Description { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesDescriptionItem> Description { get; set; }
#endif
        /// <summary>The domains property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesDomainsItem>? Domains { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesDomainsItem> Domains { get; set; }
#endif
        /// <summary>The employee_range property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesEmployeeRangeItem>? EmployeeRange { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesEmployeeRangeItem> EmployeeRange { get; set; }
#endif
        /// <summary>The estimated_arr_usd property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesEstimatedArrUsdItem>? EstimatedArrUsd { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesEstimatedArrUsdItem> EstimatedArrUsd { get; set; }
#endif
        /// <summary>The facebook property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFacebookItem>? Facebook { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFacebookItem> Facebook { get; set; }
#endif
        /// <summary>The first_calendar_interaction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFirstCalendarInteractionItem>? FirstCalendarInteraction { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFirstCalendarInteractionItem> FirstCalendarInteraction { get; set; }
#endif
        /// <summary>The first_email_interaction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFirstEmailInteractionItem>? FirstEmailInteraction { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFirstEmailInteractionItem> FirstEmailInteraction { get; set; }
#endif
        /// <summary>The first_interaction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFirstInteractionItem>? FirstInteraction { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFirstInteractionItem> FirstInteraction { get; set; }
#endif
        /// <summary>The foundation_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFoundationDateItem>? FoundationDate { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFoundationDateItem> FoundationDate { get; set; }
#endif
        /// <summary>The instagram property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesInstagramItem>? Instagram { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesInstagramItem> Instagram { get; set; }
#endif
        /// <summary>The last_calendar_interaction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLastCalendarInteractionItem>? LastCalendarInteraction { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLastCalendarInteractionItem> LastCalendarInteraction { get; set; }
#endif
        /// <summary>The last_email_interaction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLastEmailInteractionItem>? LastEmailInteraction { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLastEmailInteractionItem> LastEmailInteraction { get; set; }
#endif
        /// <summary>The last_interaction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLastInteractionItem>? LastInteraction { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLastInteractionItem> LastInteraction { get; set; }
#endif
        /// <summary>The linkedin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLinkedinItem>? Linkedin { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLinkedinItem> Linkedin { get; set; }
#endif
        /// <summary>The logo_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLogoUrlItem>? LogoUrl { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLogoUrlItem> LogoUrl { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesNameItem>? Name { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesNameItem> Name { get; set; }
#endif
        /// <summary>The next_calendar_interaction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesNextCalendarInteractionItem>? NextCalendarInteraction { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesNextCalendarInteractionItem> NextCalendarInteraction { get; set; }
#endif
        /// <summary>The primary_location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesPrimaryLocationItem>? PrimaryLocation { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesPrimaryLocationItem> PrimaryLocation { get; set; }
#endif
        /// <summary>The strongest_connection_strength property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesStrongestConnectionStrengthItem>? StrongestConnectionStrength { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesStrongestConnectionStrengthItem> StrongestConnectionStrength { get; set; }
#endif
        /// <summary>The strongest_connection_strength_legacy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesStrongestConnectionStrengthLegacyItem>? StrongestConnectionStrengthLegacy { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesStrongestConnectionStrengthLegacyItem> StrongestConnectionStrengthLegacy { get; set; }
#endif
        /// <summary>The strongest_connection_user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesStrongestConnectionUserItem>? StrongestConnectionUser { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesStrongestConnectionUserItem> StrongestConnectionUser { get; set; }
#endif
        /// <summary>The team property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesTeamItem>? Team { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesTeamItem> Team { get; set; }
#endif
        /// <summary>The twitter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesTwitterItem>? Twitter { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesTwitterItem> Twitter { get; set; }
#endif
        /// <summary>The twitter_follower_count property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesTwitterFollowerCountItem>? TwitterFollowerCount { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesTwitterFollowerCountItem> TwitterFollowerCount { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValues"/> and sets the default values.
        /// </summary>
        public GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValues()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValues"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValues CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValues();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "angellist", n => { Angellist = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesAngellistItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesAngellistItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "categories", n => { Categories = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesCategoriesItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesCategoriesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "created_at", n => { CreatedAt = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesCreatedAtItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesCreatedAtItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description", n => { Description = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesDescriptionItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesDescriptionItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "domains", n => { Domains = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesDomainsItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesDomainsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "employee_range", n => { EmployeeRange = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesEmployeeRangeItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesEmployeeRangeItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "estimated_arr_usd", n => { EstimatedArrUsd = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesEstimatedArrUsdItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesEstimatedArrUsdItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "facebook", n => { Facebook = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFacebookItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFacebookItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "first_calendar_interaction", n => { FirstCalendarInteraction = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFirstCalendarInteractionItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFirstCalendarInteractionItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "first_email_interaction", n => { FirstEmailInteraction = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFirstEmailInteractionItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFirstEmailInteractionItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "first_interaction", n => { FirstInteraction = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFirstInteractionItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFirstInteractionItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "foundation_date", n => { FoundationDate = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFoundationDateItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFoundationDateItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "instagram", n => { Instagram = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesInstagramItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesInstagramItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "last_calendar_interaction", n => { LastCalendarInteraction = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLastCalendarInteractionItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLastCalendarInteractionItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "last_email_interaction", n => { LastEmailInteraction = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLastEmailInteractionItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLastEmailInteractionItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "last_interaction", n => { LastInteraction = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLastInteractionItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLastInteractionItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "linkedin", n => { Linkedin = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLinkedinItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLinkedinItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "logo_url", n => { LogoUrl = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLogoUrlItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLogoUrlItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesNameItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesNameItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "next_calendar_interaction", n => { NextCalendarInteraction = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesNextCalendarInteractionItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesNextCalendarInteractionItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "primary_location", n => { PrimaryLocation = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesPrimaryLocationItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesPrimaryLocationItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "strongest_connection_strength", n => { StrongestConnectionStrength = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesStrongestConnectionStrengthItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesStrongestConnectionStrengthItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "strongest_connection_strength_legacy", n => { StrongestConnectionStrengthLegacy = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesStrongestConnectionStrengthLegacyItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesStrongestConnectionStrengthLegacyItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "strongest_connection_user", n => { StrongestConnectionUser = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesStrongestConnectionUserItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesStrongestConnectionUserItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "team", n => { Team = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesTeamItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesTeamItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "twitter", n => { Twitter = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesTwitterItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesTwitterItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "twitter_follower_count", n => { TwitterFollowerCount = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesTwitterFollowerCountItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesTwitterFollowerCountItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesAngellistItem>("angellist", Angellist);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesCategoriesItem>("categories", Categories);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesCreatedAtItem>("created_at", CreatedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesDescriptionItem>("description", Description);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesDomainsItem>("domains", Domains);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesEmployeeRangeItem>("employee_range", EmployeeRange);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesEstimatedArrUsdItem>("estimated_arr_usd", EstimatedArrUsd);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFacebookItem>("facebook", Facebook);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFirstCalendarInteractionItem>("first_calendar_interaction", FirstCalendarInteraction);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFirstEmailInteractionItem>("first_email_interaction", FirstEmailInteraction);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFirstInteractionItem>("first_interaction", FirstInteraction);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesFoundationDateItem>("foundation_date", FoundationDate);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesInstagramItem>("instagram", Instagram);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLastCalendarInteractionItem>("last_calendar_interaction", LastCalendarInteraction);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLastEmailInteractionItem>("last_email_interaction", LastEmailInteraction);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLastInteractionItem>("last_interaction", LastInteraction);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLinkedinItem>("linkedin", Linkedin);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesLogoUrlItem>("logo_url", LogoUrl);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesNameItem>("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesNextCalendarInteractionItem>("next_calendar_interaction", NextCalendarInteraction);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesPrimaryLocationItem>("primary_location", PrimaryLocation);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesStrongestConnectionStrengthItem>("strongest_connection_strength", StrongestConnectionStrength);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesStrongestConnectionStrengthLegacyItem>("strongest_connection_strength_legacy", StrongestConnectionStrengthLegacy);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesStrongestConnectionUserItem>("strongest_connection_user", StrongestConnectionUser);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesTeamItem>("team", Team);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesTwitterItem>("twitter", Twitter);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsCompaniesRecordsByRecordId200ResponseDataValuesTwitterFollowerCountItem>("twitter_follower_count", TwitterFollowerCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
