// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetV2ObjectsPeopleRecordsByRecordId200ResponseDataValuesPhoneNumbersItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The point in time at which this value was made &quot;active&quot;. `active_from` can be considered roughly analogous to `created_at`.</summary>
        public DateTimeOffset? ActiveFrom { get; set; }
        /// <summary>The point in time at which this value was deactivated. If `null`, the value is active.</summary>
        public DateTimeOffset? ActiveUntil { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attribute type of the value.</summary>
        public global::Soenneker.Attio.OpenApiClient.Models.PhoneNumberAttributeType? AttributeType { get; set; }
        /// <summary>The ISO 3166-1 alpha-2 country code representing the country that this phone number belongs to.</summary>
        public global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsPeopleRecordsByRecordId200ResponseDataValuesPhoneNumbersItemCountryCode? CountryCode { get; set; }
        /// <summary>The actor that created this value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsPeopleRecordsByRecordId200ResponseDataValuesPhoneNumbersItemCreatedByActor? CreatedByActor { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsPeopleRecordsByRecordId200ResponseDataValuesPhoneNumbersItemCreatedByActor CreatedByActor { get; set; }
#endif
        /// <summary>The raw, original phone number, as inputted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalPhoneNumber { get; set; }
#nullable restore
#else
        public string OriginalPhoneNumber { get; set; }
#endif
        /// <summary>The phone_number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumber { get; set; }
#nullable restore
#else
        public string PhoneNumber { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsPeopleRecordsByRecordId200ResponseDataValuesPhoneNumbersItem"/> and sets the default values.
        /// </summary>
        public GetV2ObjectsPeopleRecordsByRecordId200ResponseDataValuesPhoneNumbersItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsPeopleRecordsByRecordId200ResponseDataValuesPhoneNumbersItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsPeopleRecordsByRecordId200ResponseDataValuesPhoneNumbersItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsPeopleRecordsByRecordId200ResponseDataValuesPhoneNumbersItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active_from", n => { ActiveFrom = n.GetDateTimeOffsetValue(); } },
                { "active_until", n => { ActiveUntil = n.GetDateTimeOffsetValue(); } },
                { "attribute_type", n => { AttributeType = n.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PhoneNumberAttributeType>(); } },
                { "country_code", n => { CountryCode = n.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsPeopleRecordsByRecordId200ResponseDataValuesPhoneNumbersItemCountryCode>(); } },
                { "created_by_actor", n => { CreatedByActor = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsPeopleRecordsByRecordId200ResponseDataValuesPhoneNumbersItemCreatedByActor>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsPeopleRecordsByRecordId200ResponseDataValuesPhoneNumbersItemCreatedByActor.CreateFromDiscriminatorValue); } },
                { "original_phone_number", n => { OriginalPhoneNumber = n.GetStringValue(); } },
                { "phone_number", n => { PhoneNumber = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("active_from", ActiveFrom);
            writer.WriteDateTimeOffsetValue("active_until", ActiveUntil);
            writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PhoneNumberAttributeType>("attribute_type", AttributeType);
            writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsPeopleRecordsByRecordId200ResponseDataValuesPhoneNumbersItemCountryCode>("country_code", CountryCode);
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsPeopleRecordsByRecordId200ResponseDataValuesPhoneNumbersItemCreatedByActor>("created_by_actor", CreatedByActor);
            writer.WriteStringValue("original_phone_number", OriginalPhoneNumber);
            writer.WriteStringValue("phone_number", PhoneNumber);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
