// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>The order in which to sort the meetings. Defaults to start_asc.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetV2MeetingsSortParameter
    {
        [EnumMember(Value = "start_asc")]
        #pragma warning disable CS1591
        StartAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "start_desc")]
        #pragma warning disable CS1591
        StartDesc,
        #pragma warning restore CS1591
    }
}
