// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetV2ObjectsDealsRecordsByRecordId404ResponseCodeAnyOf1
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "not_found")]
        #pragma warning disable CS1591
        NotFound,
        #pragma warning restore CS1591
    }
}
