// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetV2Self200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The intended audience for this token, for Bearer tokens this is the same as the client_id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Aud { get; set; }
#nullable restore
#else
        public string Aud { get; set; }
#endif
        /// <summary>The ID of the workspace member who authorized this token initially. Almost every token has one, but it is omitted for the app access tokens that Attio created itself rather than on a member&apos;s behalf.</summary>
        public Guid? AuthorizedByWorkspaceMemberId { get; set; }
        /// <summary>Identifies the client the token was issued to. For app access tokens this is the app ID. Workspace access tokens have no OAuth client, so this is the workspace access token ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>The time at which this token will expire, if set, as a number of seconds since January 1 1970 UTC. Attio access tokens do not currently expire, so this is always null.</summary>
        public double? Exp { get; set; }
        /// <summary>The time at which this token was issued, as a number of seconds since January 1 1970 UTC.</summary>
        public double? Iat { get; set; }
        /// <summary>The issuer of the token. Always attio.com</summary>
        public global::Soenneker.Attio.OpenApiClient.Models.AttioComIss? Iss { get; set; }
        /// <summary>A space-separated list of scopes associated with this token</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Scope { get; set; }
#nullable restore
#else
        public string Scope { get; set; }
#endif
        /// <summary>Since Bearer tokens grant Workspace-level permissions, this property contains the workspace_id.</summary>
        public Guid? Sub { get; set; }
        /// <summary>The type of token, always Bearer.</summary>
        public global::Soenneker.Attio.OpenApiClient.Models.BearerTokenType? TokenType { get; set; }
        /// <summary>The ID of the workspace the token is scoped to.</summary>
        public Guid? WorkspaceId { get; set; }
        /// <summary>The logo URL of the workspace the token is scoped to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkspaceLogoUrl { get; set; }
#nullable restore
#else
        public string WorkspaceLogoUrl { get; set; }
#endif
        /// <summary>The name of the workspace the token is scoped to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkspaceName { get; set; }
#nullable restore
#else
        public string WorkspaceName { get; set; }
#endif
        /// <summary>The slug of the workspace the token is scoped to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkspaceSlug { get; set; }
#nullable restore
#else
        public string WorkspaceSlug { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200Response"/> and sets the default values.
        /// </summary>
        public GetV2Self200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.GetV2Self200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "aud", n => { Aud = n.GetStringValue(); } },
                { "authorized_by_workspace_member_id", n => { AuthorizedByWorkspaceMemberId = n.GetGuidValue(); } },
                { "client_id", n => { ClientId = n.GetStringValue(); } },
                { "exp", n => { Exp = n.GetDoubleValue(); } },
                { "iat", n => { Iat = n.GetDoubleValue(); } },
                { "iss", n => { Iss = n.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.AttioComIss>(); } },
                { "scope", n => { Scope = n.GetStringValue(); } },
                { "sub", n => { Sub = n.GetGuidValue(); } },
                { "token_type", n => { TokenType = n.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.BearerTokenType>(); } },
                { "workspace_id", n => { WorkspaceId = n.GetGuidValue(); } },
                { "workspace_logo_url", n => { WorkspaceLogoUrl = n.GetStringValue(); } },
                { "workspace_name", n => { WorkspaceName = n.GetStringValue(); } },
                { "workspace_slug", n => { WorkspaceSlug = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteStringValue("aud", Aud);
            writer.WriteGuidValue("authorized_by_workspace_member_id", AuthorizedByWorkspaceMemberId);
            writer.WriteStringValue("client_id", ClientId);
            writer.WriteDoubleValue("exp", Exp);
            writer.WriteDoubleValue("iat", Iat);
            writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.AttioComIss>("iss", Iss);
            writer.WriteStringValue("scope", Scope);
            writer.WriteGuidValue("sub", Sub);
            writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.BearerTokenType>("token_type", TokenType);
            writer.WriteGuidValue("workspace_id", WorkspaceId);
            writer.WriteStringValue("workspace_logo_url", WorkspaceLogoUrl);
            writer.WriteStringValue("workspace_name", WorkspaceName);
            writer.WriteStringValue("workspace_slug", WorkspaceSlug);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
