// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>
    /// An object with `attribute_slug` keys, and an array of value objects as the values. Attributes slugs (for example `workspace_id` or `name`) can be used, including custom attribute slugs.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValues : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The avatar_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesAvatarUrlItem>? AvatarUrl { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesAvatarUrlItem> AvatarUrl { get; set; }
#endif
        /// <summary>The company property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesCompanyItem>? Company { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesCompanyItem> Company { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesNameItem>? Name { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesNameItem> Name { get; set; }
#endif
        /// <summary>The users property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesUsersItem>? Users { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesUsersItem> Users { get; set; }
#endif
        /// <summary>The workspace_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesWorkspaceIdItem>? WorkspaceId { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesWorkspaceIdItem> WorkspaceId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValues"/> and sets the default values.
        /// </summary>
        public GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValues()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValues"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValues CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValues();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avatar_url", n => { AvatarUrl = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesAvatarUrlItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesAvatarUrlItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "company", n => { Company = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesCompanyItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesCompanyItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesNameItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesNameItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "users", n => { Users = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesUsersItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesUsersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "workspace_id", n => { WorkspaceId = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesWorkspaceIdItem>(global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesWorkspaceIdItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesAvatarUrlItem>("avatar_url", AvatarUrl);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesCompanyItem>("company", Company);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesNameItem>("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesUsersItem>("users", Users);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.GetV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesWorkspaceIdItem>("workspace_id", WorkspaceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
