// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>The attribute type of the value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetV2ObjectsPeopleRecordsByRecordIdAttributesByAttributeValues200ResponseDataItemAttributeType
    {
        [EnumMember(Value = "actor-reference")]
        #pragma warning disable CS1591
        ActorReference,
        #pragma warning restore CS1591
        [EnumMember(Value = "checkbox")]
        #pragma warning disable CS1591
        Checkbox,
        #pragma warning restore CS1591
        [EnumMember(Value = "currency")]
        #pragma warning disable CS1591
        Currency,
        #pragma warning restore CS1591
        [EnumMember(Value = "date")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
        [EnumMember(Value = "domain")]
        #pragma warning disable CS1591
        Domain,
        #pragma warning restore CS1591
        [EnumMember(Value = "email-address")]
        #pragma warning disable CS1591
        EmailAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "record-reference")]
        #pragma warning disable CS1591
        RecordReference,
        #pragma warning restore CS1591
        [EnumMember(Value = "interaction")]
        #pragma warning disable CS1591
        Interaction,
        #pragma warning restore CS1591
        [EnumMember(Value = "location")]
        #pragma warning disable CS1591
        Location,
        #pragma warning restore CS1591
        [EnumMember(Value = "number")]
        #pragma warning disable CS1591
        Number,
        #pragma warning restore CS1591
        [EnumMember(Value = "personal-name")]
        #pragma warning disable CS1591
        PersonalName,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone-number")]
        #pragma warning disable CS1591
        PhoneNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
        [EnumMember(Value = "rating")]
        #pragma warning disable CS1591
        Rating,
        #pragma warning restore CS1591
        [EnumMember(Value = "select")]
        #pragma warning disable CS1591
        Select,
        #pragma warning restore CS1591
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "timestamp")]
        #pragma warning disable CS1591
        Timestamp,
        #pragma warning restore CS1591
    }
}
