// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PatchV2WebhooksByWebhookIdRequestData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>One or more events the webhook is subscribed to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PatchV2WebhooksByWebhookIdRequestDataSubscriptionsItem>? Subscriptions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PatchV2WebhooksByWebhookIdRequestDataSubscriptionsItem> Subscriptions { get; set; }
#endif
        /// <summary>URL where the webhook events will be delivered to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetUrl { get; set; }
#nullable restore
#else
        public string TargetUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.PatchV2WebhooksByWebhookIdRequestData"/> and sets the default values.
        /// </summary>
        public PatchV2WebhooksByWebhookIdRequestData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PatchV2WebhooksByWebhookIdRequestData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.PatchV2WebhooksByWebhookIdRequestData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.PatchV2WebhooksByWebhookIdRequestData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "subscriptions", n => { Subscriptions = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PatchV2WebhooksByWebhookIdRequestDataSubscriptionsItem>(global::Soenneker.Attio.OpenApiClient.Models.PatchV2WebhooksByWebhookIdRequestDataSubscriptionsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "target_url", n => { TargetUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PatchV2WebhooksByWebhookIdRequestDataSubscriptionsItem>("subscriptions", Subscriptions);
            writer.WriteStringValue("target_url", TargetUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
