// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PatchV2ByTargetByIdentifierAttributesByAttributeStatusesByStatusRequestData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether arriving at this status triggers a celebration effect</summary>
        public bool? CelebrationEnabled { get; set; }
        /// <summary>Whether or not to archive the status. See our [archiving guide](/docs/archiving-vs-deleting) for more information on archiving.</summary>
        public bool? IsArchived { get; set; }
        /// <summary>Target time for a record to spend in given status expressed as a ISO-8601 duration string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetTimeInStatus { get; set; }
#nullable restore
#else
        public string TargetTimeInStatus { get; set; }
#endif
        /// <summary>The Title of the status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.PatchV2ByTargetByIdentifierAttributesByAttributeStatusesByStatusRequestData"/> and sets the default values.
        /// </summary>
        public PatchV2ByTargetByIdentifierAttributesByAttributeStatusesByStatusRequestData()
        {
            AdditionalData = new Dictionary<string, object>();
            CelebrationEnabled = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PatchV2ByTargetByIdentifierAttributesByAttributeStatusesByStatusRequestData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.PatchV2ByTargetByIdentifierAttributesByAttributeStatusesByStatusRequestData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.PatchV2ByTargetByIdentifierAttributesByAttributeStatusesByStatusRequestData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "celebration_enabled", n => { CelebrationEnabled = n.GetBoolValue(); } },
                { "is_archived", n => { IsArchived = n.GetBoolValue(); } },
                { "target_time_in_status", n => { TargetTimeInStatus = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("celebration_enabled", CelebrationEnabled);
            writer.WriteBoolValue("is_archived", IsArchived);
            writer.WriteStringValue("target_time_in_status", TargetTimeInStatus);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
