// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PatchV2ByTargetByIdentifierAttributesByAttributeOptionsByOption409ResponseCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "slug_conflict")]
        #pragma warning disable CS1591
        SlugConflict,
        #pragma warning restore CS1591
    }
}
