// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>The type of actor. [Read more information on actor types here](/docs/actors).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PatchV2ObjectsWorkspacesRecordsByRecordId200ResponseDataValuesAvatarUrlItemCreatedByActorType
    {
        [EnumMember(Value = "api-token")]
        #pragma warning disable CS1591
        ApiToken,
        #pragma warning restore CS1591
        [EnumMember(Value = "workspace-member")]
        #pragma warning disable CS1591
        WorkspaceMember,
        #pragma warning restore CS1591
        [EnumMember(Value = "system")]
        #pragma warning disable CS1591
        System,
        #pragma warning restore CS1591
        [EnumMember(Value = "app")]
        #pragma warning disable CS1591
        App,
        #pragma warning restore CS1591
    }
}
