// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PostV2Tasks400ResponseCodeAnyOf2
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "limit_reached")]
        #pragma warning disable CS1591
        LimitReached,
        #pragma warning restore CS1591
    }
}
