// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostV2ObjectsWorkspacesRecordsQueryRequestSortsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A slug or ID to identify the attribute to sort by.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Attribute { get; set; }
#nullable restore
#else
        public string Attribute { get; set; }
#endif
        /// <summary>The direction to sort the results by.</summary>
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsWorkspacesRecordsQueryRequestSortsItemDirection? Direction { get; set; }
        /// <summary>Which field on the value to sort by e.g. &quot;last_name&quot; on a name value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Field { get; set; }
#nullable restore
#else
        public string Field { get; set; }
#endif
        /// <summary>You may use the `path` property to traverse record reference attributes and parent records on list entries. `path` accepts an array of tuples where the first element of each tuple is the slug or ID of a list/object, and the second element is the slug or ID of an attribute on that list/object. The first element of the first tuple must correspond to the list or object that you are querying. For example, if you wanted to sort by the name of the parent record (a company) on a list with the slug &quot;sales&quot;, you would pass the value `[[&apos;sales&apos;, &apos;parent_record&apos;], [&apos;companies&apos;, &apos;name&apos;]]`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Path { get; set; }
#nullable restore
#else
        public UntypedNode Path { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsWorkspacesRecordsQueryRequestSortsItem"/> and sets the default values.
        /// </summary>
        public PostV2ObjectsWorkspacesRecordsQueryRequestSortsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsWorkspacesRecordsQueryRequestSortsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsWorkspacesRecordsQueryRequestSortsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsWorkspacesRecordsQueryRequestSortsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attribute", n => { Attribute = n.GetStringValue(); } },
                { "direction", n => { Direction = n.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsWorkspacesRecordsQueryRequestSortsItemDirection>(); } },
                { "field", n => { Field = n.GetStringValue(); } },
                { "path", n => { Path = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("attribute", Attribute);
            writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsWorkspacesRecordsQueryRequestSortsItemDirection>("direction", Direction);
            writer.WriteStringValue("field", Field);
            writer.WriteObjectValue<UntypedNode>("path", Path);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
