// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2FilesUpload403ResponseCodeAnyOf1"/>, <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2FilesUpload403ResponseCodeAnyOf2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PostV2FilesUpload403ResponseCode : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2FilesUpload403ResponseCodeAnyOf1"/></summary>
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2FilesUpload403ResponseCodeAnyOf1? PostV2FilesUpload403ResponseCodeAnyOf1 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2FilesUpload403ResponseCodeAnyOf2"/></summary>
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2FilesUpload403ResponseCodeAnyOf2? PostV2FilesUpload403ResponseCodeAnyOf2 { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2FilesUpload403ResponseCode"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.PostV2FilesUpload403ResponseCode CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Attio.OpenApiClient.Models.PostV2FilesUpload403ResponseCode();
            if(parseNode.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2FilesUpload403ResponseCodeAnyOf1>() is global::Soenneker.Attio.OpenApiClient.Models.PostV2FilesUpload403ResponseCodeAnyOf1 postV2FilesUpload403ResponseCodeAnyOf1Value)
            {
                result.PostV2FilesUpload403ResponseCodeAnyOf1 = postV2FilesUpload403ResponseCodeAnyOf1Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2FilesUpload403ResponseCodeAnyOf2>() is global::Soenneker.Attio.OpenApiClient.Models.PostV2FilesUpload403ResponseCodeAnyOf2 postV2FilesUpload403ResponseCodeAnyOf2Value)
            {
                result.PostV2FilesUpload403ResponseCodeAnyOf2 = postV2FilesUpload403ResponseCodeAnyOf2Value;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(PostV2FilesUpload403ResponseCodeAnyOf1 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2FilesUpload403ResponseCodeAnyOf1>(null, PostV2FilesUpload403ResponseCodeAnyOf1);
            }
            else if(PostV2FilesUpload403ResponseCodeAnyOf2 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2FilesUpload403ResponseCodeAnyOf2>(null, PostV2FilesUpload403ResponseCodeAnyOf2);
            }
        }
    }
}
#pragma warning restore CS0618
