// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItem : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The point in time at which this value was made &quot;active&quot;. `active_from` can be considered roughly analogous to `created_at`.</summary>
        public DateTimeOffset? ActiveFrom { get; set; }
        /// <summary>The point in time at which this value was deactivated. If `null`, the value is active.</summary>
        public DateTimeOffset? ActiveUntil { get; set; }
        /// <summary>The attribute type of the value.</summary>
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemAttributeType? AttributeType { get; set; }
        /// <summary>The actor that created this value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemCreatedByActor? CreatedByActor { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemCreatedByActor CreatedByActor { get; set; }
#endif
        /// <summary>When the interaction occurred.</summary>
        public DateTimeOffset? InteractedAt { get; set; }
        /// <summary>The type of interaction e.g. calendar or email.</summary>
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemInteractionType? InteractionType { get; set; }
        /// <summary>The actor that created this value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemOwnerActor? OwnerActor { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemOwnerActor OwnerActor { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active_from", n => { ActiveFrom = n.GetDateTimeOffsetValue(); } },
                { "active_until", n => { ActiveUntil = n.GetDateTimeOffsetValue(); } },
                { "attribute_type", n => { AttributeType = n.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemAttributeType>(); } },
                { "created_by_actor", n => { CreatedByActor = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemCreatedByActor>(global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemCreatedByActor.CreateFromDiscriminatorValue); } },
                { "interacted_at", n => { InteractedAt = n.GetDateTimeOffsetValue(); } },
                { "interaction_type", n => { InteractionType = n.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemInteractionType>(); } },
                { "owner_actor", n => { OwnerActor = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemOwnerActor>(global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemOwnerActor.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("active_from", ActiveFrom);
            writer.WriteDateTimeOffsetValue("active_until", ActiveUntil);
            writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemAttributeType>("attribute_type", AttributeType);
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemCreatedByActor>("created_by_actor", CreatedByActor);
            writer.WriteDateTimeOffsetValue("interacted_at", InteractedAt);
            writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemInteractionType>("interaction_type", InteractionType);
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesFirstEmailInteractionItemOwnerActor>("owner_actor", OwnerActor);
        }
    }
}
#pragma warning restore CS0618
