// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostV2ObjectsCompaniesRecords200ResponseDataValuesStrongestConnectionUserItem : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The point in time at which this value was made &quot;active&quot;. `active_from` can be considered roughly analogous to `created_at`.</summary>
        public DateTimeOffset? ActiveFrom { get; set; }
        /// <summary>The point in time at which this value was deactivated. If `null`, the value is active.</summary>
        public DateTimeOffset? ActiveUntil { get; set; }
        /// <summary>The attribute type of the value.</summary>
        public global::Soenneker.Attio.OpenApiClient.Models.ActorReferenceAttributeType? AttributeType { get; set; }
        /// <summary>The actor that created this value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesStrongestConnectionUserItemCreatedByActor? CreatedByActor { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesStrongestConnectionUserItemCreatedByActor CreatedByActor { get; set; }
#endif
        /// <summary>The ID of the referenced actor.</summary>
        public Guid? ReferencedActorId { get; set; }
        /// <summary>The type of the referenced actor. [Read more information on actor types here](/docs/actors).</summary>
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesStrongestConnectionUserItemReferencedActorType? ReferencedActorType { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesStrongestConnectionUserItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesStrongestConnectionUserItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesStrongestConnectionUserItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active_from", n => { ActiveFrom = n.GetDateTimeOffsetValue(); } },
                { "active_until", n => { ActiveUntil = n.GetDateTimeOffsetValue(); } },
                { "attribute_type", n => { AttributeType = n.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.ActorReferenceAttributeType>(); } },
                { "created_by_actor", n => { CreatedByActor = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesStrongestConnectionUserItemCreatedByActor>(global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesStrongestConnectionUserItemCreatedByActor.CreateFromDiscriminatorValue); } },
                { "referenced_actor_id", n => { ReferencedActorId = n.GetGuidValue(); } },
                { "referenced_actor_type", n => { ReferencedActorType = n.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesStrongestConnectionUserItemReferencedActorType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("active_from", ActiveFrom);
            writer.WriteDateTimeOffsetValue("active_until", ActiveUntil);
            writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.ActorReferenceAttributeType>("attribute_type", AttributeType);
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesStrongestConnectionUserItemCreatedByActor>("created_by_actor", CreatedByActor);
            writer.WriteGuidValue("referenced_actor_id", ReferencedActorId);
            writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200ResponseDataValuesStrongestConnectionUserItemReferencedActorType>("referenced_actor_type", ReferencedActorType);
        }
    }
}
#pragma warning restore CS0618
