// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>
    /// This object&apos;s keys should be the slugs or IDs of the attributes you wish to update. Below, you&apos;ll find documentation for the value types of each standard deal attribute. For information on potential custom attributes, refer to our [attribute type docs](/docs/attribute-types).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PostV2ObjectsDealsRecordsRequestDataValues : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The associated_company property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesAssociatedCompanyItem>? AssociatedCompany { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesAssociatedCompanyItem> AssociatedCompany { get; set; }
#endif
        /// <summary>The associated_people property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesAssociatedPeopleItem>? AssociatedPeople { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesAssociatedPeopleItem> AssociatedPeople { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesNameItem>? Name { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesNameItem> Name { get; set; }
#endif
        /// <summary>The owner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesOwnerItem>? Owner { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesOwnerItem> Owner { get; set; }
#endif
        /// <summary>The stage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesStageItem>? Stage { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesStageItem> Stage { get; set; }
#endif
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesValueItem>? Value { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesValueItem> Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValues"/> and sets the default values.
        /// </summary>
        public PostV2ObjectsDealsRecordsRequestDataValues()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValues"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValues CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValues();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "associated_company", n => { AssociatedCompany = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesAssociatedCompanyItem>(global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesAssociatedCompanyItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "associated_people", n => { AssociatedPeople = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesAssociatedPeopleItem>(global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesAssociatedPeopleItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesNameItem>(global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesNameItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "owner", n => { Owner = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesOwnerItem>(global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesOwnerItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "stage", n => { Stage = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesStageItem>(global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesStageItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "value", n => { Value = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesValueItem>(global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesValueItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesAssociatedCompanyItem>("associated_company", AssociatedCompany);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesAssociatedPeopleItem>("associated_people", AssociatedPeople);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesNameItem>("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesOwnerItem>("owner", Owner);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesStageItem>("stage", Stage);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsDealsRecordsRequestDataValuesValueItem>("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
