// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostV2ListsByListEntries200ResponseData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When this entry was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>A list of attribute values for the list entry (not attribute values for its parent record).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ListsByListEntries200ResponseDataEntryValues? EntryValues { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ListsByListEntries200ResponseDataEntryValues EntryValues { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ListsByListEntries200ResponseDataId? Id { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ListsByListEntries200ResponseDataId Id { get; set; }
#endif
        /// <summary>A UUID or slug identifying the object that the parent record belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentObject { get; set; }
#nullable restore
#else
        public string ParentObject { get; set; }
#endif
        /// <summary>A UUID identifying the record that is parent of the list entry.</summary>
        public Guid? ParentRecordId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2ListsByListEntries200ResponseData"/> and sets the default values.
        /// </summary>
        public PostV2ListsByListEntries200ResponseData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2ListsByListEntries200ResponseData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.PostV2ListsByListEntries200ResponseData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.PostV2ListsByListEntries200ResponseData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "entry_values", n => { EntryValues = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ListsByListEntries200ResponseDataEntryValues>(global::Soenneker.Attio.OpenApiClient.Models.PostV2ListsByListEntries200ResponseDataEntryValues.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ListsByListEntries200ResponseDataId>(global::Soenneker.Attio.OpenApiClient.Models.PostV2ListsByListEntries200ResponseDataId.CreateFromDiscriminatorValue); } },
                { "parent_object", n => { ParentObject = n.GetStringValue(); } },
                { "parent_record_id", n => { ParentRecordId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ListsByListEntries200ResponseDataEntryValues>("entry_values", EntryValues);
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ListsByListEntries200ResponseDataId>("id", Id);
            writer.WriteStringValue("parent_object", ParentObject);
            writer.WriteGuidValue("parent_record_id", ParentRecordId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
