// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes List&lt;global::Soenneker.Attio.OpenApiClient.Models.PostV2TasksRequestDataLinkedRecordsAnyOf2Item&gt;, List&lt;string&gt;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PostV2TasksRequestDataLinkedRecords : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type List&lt;global::Soenneker.Attio.OpenApiClient.Models.PostV2TasksRequestDataLinkedRecordsAnyOf2Item&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2TasksRequestDataLinkedRecordsAnyOf2Item>? PostV2TasksRequestDataLinkedRecordsAnyOf2Item { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2TasksRequestDataLinkedRecordsAnyOf2Item> PostV2TasksRequestDataLinkedRecordsAnyOf2Item { get; set; }
#endif
        /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? String { get; set; }
#nullable restore
#else
        public List<string> String { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2TasksRequestDataLinkedRecords"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.PostV2TasksRequestDataLinkedRecords CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Attio.OpenApiClient.Models.PostV2TasksRequestDataLinkedRecords();
            if(parseNode.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2TasksRequestDataLinkedRecordsAnyOf2Item>(global::Soenneker.Attio.OpenApiClient.Models.PostV2TasksRequestDataLinkedRecordsAnyOf2Item.CreateFromDiscriminatorValue)?.AsList() is List<global::Soenneker.Attio.OpenApiClient.Models.PostV2TasksRequestDataLinkedRecordsAnyOf2Item> postV2TasksRequestDataLinkedRecordsAnyOf2ItemValue)
            {
                result.PostV2TasksRequestDataLinkedRecordsAnyOf2Item = postV2TasksRequestDataLinkedRecordsAnyOf2ItemValue;
            }
            else if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
            {
                result.String = stringValue;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(PostV2TasksRequestDataLinkedRecordsAnyOf2Item != null)
            {
                writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2TasksRequestDataLinkedRecordsAnyOf2Item>(null, PostV2TasksRequestDataLinkedRecordsAnyOf2Item);
            }
            else if(String != null)
            {
                writer.WriteCollectionOfPrimitiveValues<string>(null, String);
            }
        }
    }
}
#pragma warning restore CS0618
