// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostV2ObjectsCompaniesRecordsQueryRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An object used to filter results to a subset of records. See the [full guide to filtering and sorting here](/rest-api/guides/filtering-and-sorting).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsQueryRequestFilter? Filter { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsQueryRequestFilter Filter { get; set; }
#endif
        /// <summary>The maximum number of results to return. Defaults to 500. See the [full guide to pagination here](/rest-api/guides/pagination).</summary>
        public double? Limit { get; set; }
        /// <summary>The number of results to skip over before returning. Defaults to 0. See the [full guide to pagination here](/rest-api/guides/pagination).</summary>
        public double? Offset { get; set; }
        /// <summary>An object used to sort results. See the [full guide to filtering and sorting here](/rest-api/guides/filtering-and-sorting).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsQueryRequestSortsItem>? Sorts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsQueryRequestSortsItem> Sorts { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsQueryRequest"/> and sets the default values.
        /// </summary>
        public PostV2ObjectsCompaniesRecordsQueryRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsQueryRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsQueryRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsQueryRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filter", n => { Filter = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsQueryRequestFilter>(global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsQueryRequestFilter.CreateFromDiscriminatorValue); } },
                { "limit", n => { Limit = n.GetDoubleValue(); } },
                { "offset", n => { Offset = n.GetDoubleValue(); } },
                { "sorts", n => { Sorts = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsQueryRequestSortsItem>(global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsQueryRequestSortsItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsQueryRequestFilter>("filter", Filter);
            writer.WriteDoubleValue("limit", Limit);
            writer.WriteDoubleValue("offset", Offset);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsQueryRequestSortsItem>("sorts", Sorts);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
