// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>Creates a connected file entry.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostV2FilesRequestConnectedFileFileType
    {
        [EnumMember(Value = "connected-file")]
        #pragma warning disable CS1591
        ConnectedFile,
        #pragma warning restore CS1591
    }
}
