// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>The attribute type of the value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostV2ObjectsCompaniesRecordsQuery200ResponseDataItemValuesFirstEmailInteractionItemAttributeType
    {
        [EnumMember(Value = "interaction")]
        #pragma warning disable CS1591
        Interaction,
        #pragma warning restore CS1591
    }
}
