// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PostV2ObjectsPeopleRecords400ResponseCodeAnyOf2
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "particle_gate_violation")]
        #pragma warning disable CS1591
        ParticleGateViolation,
        #pragma warning restore CS1591
    }
}
