// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostV2ObjectsCompaniesRecordsRequestDataValuesFoundationDateItem : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>A timestamp value represents a single, universal moment in time using an ISO 8601 formatted string. This means that a timestamp consists of a date, a time (with nanosecond precision), and a time zone. Attio will coerce timestamps which do not provide full nanosecond precision and UTC is assumed if no time zone is provided. For example, &quot;2023&quot;, &quot;2023-01&quot;, &quot;2023-01-02&quot;, &quot;2023-01-02T13:00&quot;, &quot;2023-01-02T13:00:00&quot;, and &quot;2023-01-02T13:00:00.000000000&quot; will all be coerced to &quot;2023-01-02T13:00:00.000000000Z&quot;. Timestamps are always returned in UTC. For example, writing a timestamp value using the string &quot;2023-01-02T13:00:00.000000000+02:00&quot; will result in the value &quot;2023-01-02T11:00:00.000000000Z&quot; being returned. The maximum date is &quot;9999-12-31T23:59:59.999999999Z&quot;.</summary>
        public Date? Value { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsRequestDataValuesFoundationDateItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsRequestDataValuesFoundationDateItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsRequestDataValuesFoundationDateItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "value", n => { Value = n.GetDateValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateValue("value", Value);
        }
    }
}
#pragma warning restore CS0618
