// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostV2NotesRequestData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The main content of the note, formatted according to the value provided in the `format` field. Use `\n` for line breaks in `plaintext`. For `markdown`, utilize the supported syntax elements to structure and style your note.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Content { get; set; }
#nullable restore
#else
        public string Content { get; set; }
#endif
        /// <summary>`created_at` will default to the current time. However, if you wish to backdate a note for migration or other purposes, you can override with a custom `created_at` value. Note that dates before 1970 or in the future are not allowed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>Specify the format for the note&apos;s content. Choose from:- `plaintext`: Standard text format where `\n` signifies a new line.- `markdown`: Enables rich text formatting using a subset of Markdown syntax:  - **Headings**: Levels 1-3 (`#`, `##`, `###`).  - **Lists**: Unordered (`-`, `*`, `+`) and ordered (`1.`, `2.`).  - **Text styles**: Bold (`**bold**` or `__bold__`), italic (`*italic*` or `_italic_`), strikethrough (`~~strikethrough~~`), and highlight (`==highlighted==`).  - **Links**: Standard Markdown links (`[link text](https://example.com)`).  *Note: While the Attio interface supports image embeds, they cannot currently be added or retrieved via the API&apos;s markdown format.*</summary>
        public global::Soenneker.Attio.OpenApiClient.Models.PostV2NotesRequestDataFormat? Format { get; set; }
        /// <summary>An optional ID to associate this note with a meeting. If provided, the meeting must exist. Use `null` to explicitly set no meeting association.</summary>
        public Guid? MeetingId { get; set; }
        /// <summary>The ID or slug of the parent object the note belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentObject { get; set; }
#nullable restore
#else
        public string ParentObject { get; set; }
#endif
        /// <summary>The ID of the parent record the note belongs to.</summary>
        public Guid? ParentRecordId { get; set; }
        /// <summary>The note title. The title is plaintext only and has no formatting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2NotesRequestData"/> and sets the default values.
        /// </summary>
        public PostV2NotesRequestData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2NotesRequestData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.PostV2NotesRequestData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.PostV2NotesRequestData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content", n => { Content = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "format", n => { Format = n.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2NotesRequestDataFormat>(); } },
                { "meeting_id", n => { MeetingId = n.GetGuidValue(); } },
                { "parent_object", n => { ParentObject = n.GetStringValue(); } },
                { "parent_record_id", n => { ParentRecordId = n.GetGuidValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("content", Content);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PostV2NotesRequestDataFormat>("format", Format);
            writer.WriteGuidValue("meeting_id", MeetingId);
            writer.WriteStringValue("parent_object", ParentObject);
            writer.WriteGuidValue("parent_record_id", ParentRecordId);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
