// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PutV2ObjectsCompaniesRecords200ResponseDataValuesDomainsItem : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The point in time at which this value was made &quot;active&quot;. `active_from` can be considered roughly analogous to `created_at`.</summary>
        public DateTimeOffset? ActiveFrom { get; set; }
        /// <summary>The point in time at which this value was deactivated. If `null`, the value is active.</summary>
        public DateTimeOffset? ActiveUntil { get; set; }
        /// <summary>The attribute type of the value.</summary>
        public global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200ResponseDataValuesDomainsItemAttributeType? AttributeType { get; set; }
        /// <summary>The actor that created this value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200ResponseDataValuesDomainsItemCreatedByActor? CreatedByActor { get; set; }
#nullable restore
#else
        public global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200ResponseDataValuesDomainsItemCreatedByActor CreatedByActor { get; set; }
#endif
        /// <summary>The domain property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Domain { get; set; }
#nullable restore
#else
        public string Domain { get; set; }
#endif
        /// <summary>The root_domain property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RootDomain { get; set; }
#nullable restore
#else
        public string RootDomain { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200ResponseDataValuesDomainsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200ResponseDataValuesDomainsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200ResponseDataValuesDomainsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active_from", n => { ActiveFrom = n.GetDateTimeOffsetValue(); } },
                { "active_until", n => { ActiveUntil = n.GetDateTimeOffsetValue(); } },
                { "attribute_type", n => { AttributeType = n.GetEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200ResponseDataValuesDomainsItemAttributeType>(); } },
                { "created_by_actor", n => { CreatedByActor = n.GetObjectValue<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200ResponseDataValuesDomainsItemCreatedByActor>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200ResponseDataValuesDomainsItemCreatedByActor.CreateFromDiscriminatorValue); } },
                { "domain", n => { Domain = n.GetStringValue(); } },
                { "root_domain", n => { RootDomain = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("active_from", ActiveFrom);
            writer.WriteDateTimeOffsetValue("active_until", ActiveUntil);
            writer.WriteEnumValue<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200ResponseDataValuesDomainsItemAttributeType>("attribute_type", AttributeType);
            writer.WriteObjectValue<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200ResponseDataValuesDomainsItemCreatedByActor>("created_by_actor", CreatedByActor);
            writer.WriteStringValue("domain", Domain);
            writer.WriteStringValue("root_domain", RootDomain);
        }
    }
}
#pragma warning restore CS0618
