// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>
    /// This object&apos;s keys should be the slugs or IDs of the attributes you wish to update. Below, you&apos;ll find documentation for the value types of each standard company attribute. For information on potential custom attributes, refer to our [attribute type docs](/docs/attribute-types).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PutV2ObjectsCompaniesRecordsRequestDataValues : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The angellist property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesAngellistItem>? Angellist { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesAngellistItem> Angellist { get; set; }
#endif
        /// <summary>The categories property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesCategoriesItem>? Categories { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesCategoriesItem> Categories { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesDescriptionItem>? Description { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesDescriptionItem> Description { get; set; }
#endif
        /// <summary>The domains property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesDomainsItem>? Domains { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesDomainsItem> Domains { get; set; }
#endif
        /// <summary>The employee_range property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesEmployeeRangeItem>? EmployeeRange { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesEmployeeRangeItem> EmployeeRange { get; set; }
#endif
        /// <summary>The estimated_arr_usd property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesEstimatedArrUsdItem>? EstimatedArrUsd { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesEstimatedArrUsdItem> EstimatedArrUsd { get; set; }
#endif
        /// <summary>The facebook property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesFacebookItem>? Facebook { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesFacebookItem> Facebook { get; set; }
#endif
        /// <summary>The foundation_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesFoundationDateItem>? FoundationDate { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesFoundationDateItem> FoundationDate { get; set; }
#endif
        /// <summary>The instagram property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesInstagramItem>? Instagram { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesInstagramItem> Instagram { get; set; }
#endif
        /// <summary>The linkedin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesLinkedinItem>? Linkedin { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesLinkedinItem> Linkedin { get; set; }
#endif
        /// <summary>The logo_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesLogoUrlItem>? LogoUrl { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesLogoUrlItem> LogoUrl { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesNameItem>? Name { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesNameItem> Name { get; set; }
#endif
        /// <summary>The primary_location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesPrimaryLocationItem>? PrimaryLocation { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesPrimaryLocationItem> PrimaryLocation { get; set; }
#endif
        /// <summary>The team property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesTeamItem>? Team { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesTeamItem> Team { get; set; }
#endif
        /// <summary>The twitter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesTwitterItem>? Twitter { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesTwitterItem> Twitter { get; set; }
#endif
        /// <summary>The twitter_follower_count property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesTwitterFollowerCountItem>? TwitterFollowerCount { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesTwitterFollowerCountItem> TwitterFollowerCount { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValues"/> and sets the default values.
        /// </summary>
        public PutV2ObjectsCompaniesRecordsRequestDataValues()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValues"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValues CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValues();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "angellist", n => { Angellist = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesAngellistItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesAngellistItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "categories", n => { Categories = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesCategoriesItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesCategoriesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description", n => { Description = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesDescriptionItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesDescriptionItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "domains", n => { Domains = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesDomainsItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesDomainsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "employee_range", n => { EmployeeRange = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesEmployeeRangeItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesEmployeeRangeItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "estimated_arr_usd", n => { EstimatedArrUsd = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesEstimatedArrUsdItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesEstimatedArrUsdItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "facebook", n => { Facebook = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesFacebookItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesFacebookItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "foundation_date", n => { FoundationDate = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesFoundationDateItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesFoundationDateItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "instagram", n => { Instagram = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesInstagramItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesInstagramItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "linkedin", n => { Linkedin = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesLinkedinItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesLinkedinItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "logo_url", n => { LogoUrl = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesLogoUrlItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesLogoUrlItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesNameItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesNameItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "primary_location", n => { PrimaryLocation = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesPrimaryLocationItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesPrimaryLocationItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "team", n => { Team = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesTeamItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesTeamItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "twitter", n => { Twitter = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesTwitterItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesTwitterItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "twitter_follower_count", n => { TwitterFollowerCount = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesTwitterFollowerCountItem>(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesTwitterFollowerCountItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesAngellistItem>("angellist", Angellist);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesCategoriesItem>("categories", Categories);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesDescriptionItem>("description", Description);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesDomainsItem>("domains", Domains);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesEmployeeRangeItem>("employee_range", EmployeeRange);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesEstimatedArrUsdItem>("estimated_arr_usd", EstimatedArrUsd);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesFacebookItem>("facebook", Facebook);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesFoundationDateItem>("foundation_date", FoundationDate);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesInstagramItem>("instagram", Instagram);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesLinkedinItem>("linkedin", Linkedin);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesLogoUrlItem>("logo_url", LogoUrl);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesNameItem>("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesPrimaryLocationItem>("primary_location", PrimaryLocation);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesTeamItem>("team", Team);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesTwitterItem>("twitter", Twitter);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequestDataValuesTwitterFollowerCountItem>("twitter_follower_count", TwitterFollowerCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
