// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TaskDeletedEventType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "task.deleted")]
        #pragma warning disable CS1591
        TaskDeleted,
        #pragma warning restore CS1591
    }
}
