// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ValidationTypeCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "validation_type")]
        #pragma warning disable CS1591
        ValidationType,
        #pragma warning restore CS1591
    }
}
