// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>
    /// This event is fired whenever a list attribute is updated (e.g. when changing the name of the &quot;Owner&quot; attribute to &quot;Proprietor&quot;).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebhooksListAttributeUpdatedRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An array of webhook events. Currently, each delivery contains exactly one event, but this may change in the future to support batching.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Attio.OpenApiClient.Models.WebhooksListAttributeUpdatedRequestEventsItem>? Events { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Attio.OpenApiClient.Models.WebhooksListAttributeUpdatedRequestEventsItem> Events { get; set; }
#endif
        /// <summary>The ID of the webhook that triggered this delivery.</summary>
        public Guid? WebhookId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.Models.WebhooksListAttributeUpdatedRequest"/> and sets the default values.
        /// </summary>
        public WebhooksListAttributeUpdatedRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.WebhooksListAttributeUpdatedRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Attio.OpenApiClient.Models.WebhooksListAttributeUpdatedRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Attio.OpenApiClient.Models.WebhooksListAttributeUpdatedRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "events", n => { Events = n.GetCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.WebhooksListAttributeUpdatedRequestEventsItem>(global::Soenneker.Attio.OpenApiClient.Models.WebhooksListAttributeUpdatedRequestEventsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "webhook_id", n => { WebhookId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Attio.OpenApiClient.Models.WebhooksListAttributeUpdatedRequestEventsItem>("events", Events);
            writer.WriteGuidValue("webhook_id", WebhookId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
