// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WorkspaceMemberCreatedEventType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "workspace-member.created")]
        #pragma warning disable CS1591
        WorkspaceMemberCreated,
        #pragma warning restore CS1591
    }
}
