// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>The type of the referenced actor. Currently, only workspace members can be written into actor reference attributes. [Read more information on actor types here](/docs/actors).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WorkspaceMemberReferencedActorType
    {
        [EnumMember(Value = "workspace-member")]
        #pragma warning disable CS1591
        WorkspaceMember,
        #pragma warning restore CS1591
    }
}
