// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Attio.OpenApiClient.Models
{
    /// <summary>Whether the workspace member is suspended or not and what level of privileges they have inside the workspace. We do not delete workspace members so that you can successfully attribute past actions to suspended workspace members.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WorkspaceMemberAccessLevel
    {
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "member")]
        #pragma warning disable CS1591
        Member,
        #pragma warning restore CS1591
        [EnumMember(Value = "suspended")]
        #pragma warning disable CS1591
        Suspended,
        #pragma warning restore CS1591
    }
}
