// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Attio.OpenApiClient.Models;
using Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.Item;
using Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.Query;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\objects\companies\records
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RecordsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The query property</summary>
        public global::Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.Query.QueryRequestBuilder Query
        {
            get => new global::Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.Query.QueryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Attio.OpenApiClient.v2.objects.companies.records.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.Item.WithRecordItemRequestBuilder"/></returns>
        public global::Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.Item.WithRecordItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("recordId", position);
                return new global::Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.Item.WithRecordItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.RecordsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecordsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/objects/companies/records", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.RecordsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecordsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/objects/companies/records", rawUrl)
        {
        }
        /// <summary>
        /// Creates a new company record. This endpoint will throw on conflicts of unique attributes, like `domains`. If you would prefer to update company records on conflicts, please use the Assert company record endpoint instead. Please note, the `logo_url` attribute cannot currently be set via the API.Required scopes: `record_permission:read-write`, `object_configuration:read`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords404Response">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200Response?> PostAsync(global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200Response> PostAsync(global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords400Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords403Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords404Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200Response>(requestInfo, global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecords200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Use this endpoint to create or update company records, using a unique attribute to search for existing companies (for example, the `domains` attribute). If a company is found with the same value for the matching attribute, that company will be updated. If no company with the same value for the matching attribute is found, a new company will be created instead. If you would like to avoid matching, please use the Create company endpoint.If the matching attribute is a multiselect attribute, new values will be added and existing values will not be deleted. For any other multiselect attribute, all values will be either created or deleted as necessary to match the list of supplied values.Required scopes: `record_permission:read-write`, `object_configuration:read`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords404Response">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200Response?> PutAsync(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequest body, Action<RequestConfiguration<global::Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.RecordsRequestBuilder.RecordsRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200Response> PutAsync(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequest body, Action<RequestConfiguration<global::Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.RecordsRequestBuilder.RecordsRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords400Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords403Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords404Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200Response>(requestInfo, global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecords200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new company record. This endpoint will throw on conflicts of unique attributes, like `domains`. If you would prefer to update company records on conflicts, please use the Assert company record endpoint instead. Please note, the `logo_url` attribute cannot currently be set via the API.Required scopes: `record_permission:read-write`, `object_configuration:read`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Attio.OpenApiClient.Models.PostV2ObjectsCompaniesRecordsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Use this endpoint to create or update company records, using a unique attribute to search for existing companies (for example, the `domains` attribute). If a company is found with the same value for the matching attribute, that company will be updated. If no company with the same value for the matching attribute is found, a new company will be created instead. If you would like to avoid matching, please use the Create company endpoint.If the matching attribute is a multiselect attribute, new values will be added and existing values will not be deleted. For any other multiselect attribute, all values will be either created or deleted as necessary to match the list of supplied values.Required scopes: `record_permission:read-write`, `object_configuration:read`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequest body, Action<RequestConfiguration<global::Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.RecordsRequestBuilder.RecordsRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Attio.OpenApiClient.Models.PutV2ObjectsCompaniesRecordsRequest body, Action<RequestConfiguration<global::Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.RecordsRequestBuilder.RecordsRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, "{+baseurl}/v2/objects/companies/records?matching_attribute={matching_attribute}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.RecordsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.RecordsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Attio.OpenApiClient.V2.Objects.Companies.Records.RecordsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Use this endpoint to create or update company records, using a unique attribute to search for existing companies (for example, the `domains` attribute). If a company is found with the same value for the matching attribute, that company will be updated. If no company with the same value for the matching attribute is found, a new company will be created instead. If you would like to avoid matching, please use the Create company endpoint.If the matching attribute is a multiselect attribute, new values will be added and existing values will not be deleted. For any other multiselect attribute, all values will be either created or deleted as necessary to match the list of supplied values.Required scopes: `record_permission:read-write`, `object_configuration:read`.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecordsRequestBuilderPutQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("matching_attribute")]
            public string? MatchingAttribute { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("matching_attribute")]
            public string MatchingAttribute { get; set; }
            #pragma warning restore CS1591
#endif
        }
    }
}
#pragma warning restore CS0618
